<div class="row">
	<div class="columns six">
		<div class="card">
			<div class="card_head">
				<h5 class="card_head_title">System Health Breakdown</h5>
			</div>
			<div class="card_body">
				<table style="width:100%;" class="table invisible">
					<tbody>
						<tr>
							<td>Show Errors</td>
							<td><?php echo $config->application->showErrors === true ? 'On' : 'Off'; ?></td>
						</tr>
						<tr>
							<td>Log Errors</td>
							<td><?php echo $config->application->logErrors === true ? 'On' : 'Off'; ?></td>
						</tr>
						<tr>
							<th></th>
							<td></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>