<div class="row">
	<div class="columns twelve">
		<h4>Cards</h4>
		<div class="row">
			<div class="columns six">
				<div class="card">
					<div class="card_head">
						<h5 class="card_head_title">Card heading</h5>
					</div>
					<div class="card_body">
						Card Body
					</div>
					<div class="card_foot">
						Card Footer
					</div>
				</div>
			</div>
			<div class="columns six">
				<pre>
					<code>
						<div class="card"></div>
					</code>
				</pre>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="columns twelve">
		<h4>Buttons</h4>
		<div class="row">
			<div class="columns six">
				<button class="btn btn-primary">Primary Button</button>
				<a class="btn btn-secondary">Secondary Button</a>
			</div>
			<div class="columns six">
			</div>
		</div>
		<div class="row">
			<div class="columns six">
				<button class="btn btn-success">Success Button</button>
				<a class="btn btn-danger">Danger Button</a>
				<a class="btn btn-info">Info Button</a>
			</div>
			<div class="columns six">
			</div>
		</div>
		<div class="row">
			<div class="columns six">
				<a class="btn btn-primary btn-lg">Large Button</a>
				<button class="btn btn-primary">Normal Button</button>
				<a class="btn btn-primary btn-sm">Small Button</a>
				
			</div>
			<div class="columns six">
			</div>
		</div>
	</div>
</div>