<!-- BEGIN: Brand -->
<div class="m-stack__item m-brand  m-brand--skin-light ">
	<div class="m-stack m-stack--ver m-stack--general">
		<div class="m-stack__item m-stack__item--middle m-brand__logo">
			<a href="/" class="m-brand__logo-wrapper">
				<img alt="" src="/img/logo.png" height="70"/>
			</a>
		</div>
		<div class="m-stack__item m-stack__item--middle m-brand__tools">
			<!-- BEGIN: Responsive Aside Left Menu Toggler -->
			<a href="javascript:;" id="m_aside_left_offcanvas_toggle" class="m-brand__icon m-brand__toggler m-brand__toggler--left m--visible-tablet-and-mobile-inline-block">
				<span></span>
			</a>
			<!-- END -->
			<!-- BEGIN: Topbar Toggler -->
			<a id="m_aside_header_topbar_mobile_toggle" href="javascript:;" class="m-brand__icon m--visible-tablet-and-mobile-inline-block">
				<i class="flaticon-more"></i>
			</a>
			<!-- BEGIN: Topbar Toggler -->
		</div>
	</div>
</div>
<!-- END: Brand -->