<!-- begin::Footer -->
<footer class="m-grid__item		m-footer ">
	<div class="m-container m-container--fluid m-container--full-height m-page__container">
		<div class="m-stack m-stack--flex-tablet-and-mobile m-stack--ver m-stack--desktop">
			<div class="m-stack__item m-stack__item--left m-stack__item--middle m-stack__item--last">
				<span class="m-footer__copyright">
					Manchester First Aid Training &copy; <?php echo date('Y'); ?> - Powered By 
					<a href="https://www.cleartwo.co.uk" target ="_blank"  class="m-link">
						<?php echo $this->config->application->company;?>
					</a>
				</span>
			</div>
			
		</div>
	</div>
</footer>
<!-- end::Footer -->