<!-- BEGIN: Topbar -->
<div id="m_header_topbar" class="m-topbar  m-stack m-stack--ver m-stack--general">
	<!--[html-partial:include:{"file":"partials\/_topbar-search-default.html"}]/-->
	<div class="m-stack__item m-topbar__nav-wrapper">
		<ul class="m-topbar__nav m-nav m-nav--inline">
			<!--[html-partial:include:{"file":"partials\/_topbar-notifications.html"}]/-->
            <!--[html-partial:include:{"file":"partials\/_topbar-quick-actions.html"}]/-->
			<?php $this->partial("partials/topbaruserprofile"); ?>
		</ul>
	</div>
</div>
<!-- END: Topbar -->