<?php echo $this->flashSession->output(); ?>
<?php echo $this->flash->output(); ?>
<form method="post" class="form" autocomplete="off" action="/users/changePassword">
		<div class="card-body">
       		<div class="form-group">
				<label>Password</label>
				<?php echo $form->render('password');?>
		</div>
		<div class="form-group">
			<label>Confirm Password</label>
			<?php echo $form->render('confirmPassword');?>
		</div>
	</div>
	<div class="card-footer">
		<div class="row">
			<div class="col text-left">
				<?php echo $form->render('Submit');?>
			</div>
		</div>
	</div>
</form>