<!-- begin::Topbar -->
<div class="m-stack__item m-stack__item--right m-header-head" id="m_header_nav">
	<div id="m_header_topbar" class="m-topbar  m-stack m-stack--ver m-stack--general">
		<div class="m-stack__item m-topbar__nav-wrapper">
			<ul class="m-topbar__nav m-nav m-nav--inline">
				<?php $this->partial("partials/theme10/topbar-user-profile"); ?>
			</ul>
		</div>
	</div>
</div>
<!-- end::Topbar -->