<!-- begin::Header -->
<header id="m_header" class="m-grid__item m-header " m-minimize="minimize" m-minimize-mobile="minimize" m-minimize-offset="10"
	m-minimize-mobile-offset="10">
	<div class="m-header__top">
		<div class="m-container m-container--fluid m-container--full-height m-page__container">
			<div class="m-stack m-stack--ver m-stack--desktop">
				<?php $this->partial("partials/theme10/header-brand"); ?>
				<?php $this->partial("partials/theme10/header-topbar"); ?>
			</div>
		</div>
	</div>
	<div class="m-header__bottom">
		<div class="m-container m-container--fluid m-container--full-height m-page__container">
			<div class="m-stack m-stack--ver m-stack--desktop">
				<?php $this->partial("partials/theme10/header-hor-menu"); ?>
			</div>
		</div>
	</div>
</header>
<!-- end::Header -->
