<!-- begin::Brand -->
<div class="m-stack__item m-brand m-stack__item--left">
	<div class="m-stack m-stack--ver m-stack--general m-stack--inline">
		<div class="m-stack__item m-stack__item--middle m-brand__logo">
			<a href="/dashboard" class="m-brand__logo-wrapper">
				<img alt="LAPD System" src="/img/logo.svg" style="width: 65px;" class="m-brand__logo-desktop" />
				<img alt="LAPD System" style="width: 35px;" src="/img/logo.svg" class="m-brand__logo-mobile" />
			</a>
		</div>
		<div class="m-stack__item m-stack__item--middle m-brand__tools">

			<!-- begin::Responsive Header Menu Toggler-->
			<a id="m_aside_header_menu_mobile_toggle" href="javascript:;" class="m-brand__icon m-brand__toggler m--visible-tablet-and-mobile-inline-block">
				<span></span>
			</a>
			<!-- end::Responsive Header Menu Toggler-->
			<!-- begin::Topbar Toggler-->
			<a id="m_aside_header_topbar_mobile_toggle" href="javascript:;" class="m-brand__icon m--visible-tablet-and-mobile-inline-block">
				<i class="flaticon-more"></i>
			</a>
			<!--end::Topbar Toggler-->
		</div>
	</div>
</div>
<!-- end::Brand -->