<?php
$controller = $this->router->getControllerName();
$active 	= 'm-menu__item--active';
$activeTab	= 'm-menu__item--active m-menu__item--active-tab';

$ident = $this->auth->getIdentity();
if (is_array($ident)):
?>
<!-- begin::Horizontal Menu -->
<div class="m-stack__item m-stack__item--fluid m-header-menu-wrapper">
	<button class="m-aside-header-menu-mobile-close  m-aside-header-menu-mobile-close--skin-light " id="m_aside_header_menu_mobile_close_btn">
		<i class="la la-close"></i>
	</button>
	<div id="m_header_menu" class="m-header-menu m-aside-header-menu-mobile m-aside-header-menu-mobile--offcanvas  m-header-menu--skin-dark m-header-menu--submenu-skin-light m-aside-header-menu-mobile--skin-light m-aside-header-menu-mobile--submenu-skin-light ">
		<ul class="m-menu__nav  m-menu__nav--submenu-arrow ">
			<!-- Dashboard menu -->
			<li class="m-menu__item <?php if (in_array($controller, ['dashboard', 'station'])){ echo $activeTab; }; ?> m-menu__item--submenu m-menu__item--tabs" m-menu-submenu-toggle="tab" aria-haspopup="true">
				<a href="javascript:;" class="m-menu__link m-menu__toggle" title="Non functional dummy link">
				<span class="m-menu__link-text">Dashboard</span>
					<i class="m-menu__hor-arrow la la-angle-down"></i><i class="m-menu__ver-arrow la la-angle-right"></i>
				</a>
				<div class="m-menu__submenu m-menu__submenu--classic m-menu__submenu--left m-menu__submenu--tabs">
					<span class="m-menu__arrow m-menu__arrow--adjust"></span>
					<ul class="m-menu__subnav">
						<li class="m-menu__item <?php if ($controller == 'dashboard'){ echo $active; }; ?>" m-menu-link-redirect="1" aria-haspopup="true">
							<a href="/dashboard" class="m-menu__link ">
								<i class="m-menu__link-icon flaticon-support"></i><span class="m-menu__link-text">Dashboard</span>
							</a>
						</li>
						<li class="m-menu__item <?php if ($controller == 'station'){ echo $active; }; ?>" m-menu-link-redirect="1" aria-haspopup="true">
							<a href="/station" class="m-menu__link ">
								<i class="m-menu__link-icon flaticon-support"></i><span class="m-menu__link-text">Stations</span>
							</a>
						</li>
					</ul>
				</div>
			</li>
			<!-- Customer menu -->
			<li class="m-menu__item <?php if (in_array($controller, ['customer', 'address'])){ echo $activeTab; }; ?> m-menu__item--submenu m-menu__item--tabs" m-menu-submenu-toggle="tab" aria-haspopup="true">
				<a href="javascript:;" class="m-menu__link m-menu__toggle" title="Non functional dummy link">
				<span class="m-menu__link-text">Customers</span>
					<i class="m-menu__hor-arrow la la-angle-down"></i><i class="m-menu__ver-arrow la la-angle-right"></i>
				</a>
				<div class="m-menu__submenu m-menu__submenu--classic m-menu__submenu--left m-menu__submenu--tabs">
					<span class="m-menu__arrow m-menu__arrow--adjust"></span>
					<ul class="m-menu__subnav">
						<li class="m-menu__item <?php if ($controller == 'customer'){ echo $active; }; ?>" m-menu-link-redirect="1" aria-haspopup="true">
							<a href="/customer" class="m-menu__link ">
								<i class="m-menu__link-icon flaticon-support"></i><span class="m-menu__link-text">Customer</span>
							</a>
						</li>
						<li class="m-menu__item <?php if ($controller == 'address'){ echo $active; }; ?>" m-menu-link-redirect="1" aria-haspopup="true">
							<a href="/address" class="m-menu__link ">
								<i class="m-menu__link-icon flaticon-support"></i><span class="m-menu__link-text">address</span>
							</a>
						</li>
					</ul>
				</div>
			</li>
			<!-- Products menu -->
			<li class="m-menu__item <?php if (in_array($controller, ['product', 'category', 'extra', 'option', 'optionset'])){ echo $activeTab; }; ?> m-menu__item--submenu m-menu__item--tabs" m-menu-submenu-toggle="tab" aria-haspopup="true">
				<a href="javascript:;" class="m-menu__link m-menu__toggle" title="Non functional dummy link">
				<span class="m-menu__link-text">Products</span>
					<i class="m-menu__hor-arrow la la-angle-down"></i><i class="m-menu__ver-arrow la la-angle-right"></i>
				</a>
				<div class="m-menu__submenu m-menu__submenu--classic m-menu__submenu--left m-menu__submenu--tabs">
					<span class="m-menu__arrow m-menu__arrow--adjust"></span>
					<ul class="m-menu__subnav">
						<li class="m-menu__item <?php if ($controller == 'product'){ echo $active; }; ?>" m-menu-link-redirect="1" aria-haspopup="true">
							<a href="/product" class="m-menu__link ">
								<i class="m-menu__link-icon flaticon-support"></i><span class="m-menu__link-text">Products</span>
							</a>
						</li>
						<li class="m-menu__item <?php if ($controller == 'category'){ echo $active; }; ?>" m-menu-link-redirect="1" aria-haspopup="true">
							<a href="/category" class="m-menu__link ">
								<i class="m-menu__link-icon flaticon-support"></i><span class="m-menu__link-text">Category</span>
							</a>
						</li>
						<li class="m-menu__item <?php if ($controller == 'extra'){ echo $active; }; ?>" m-menu-link-redirect="1" aria-haspopup="true">
							<a href="/extra" class="m-menu__link ">
								<i class="m-menu__link-icon flaticon-support"></i><span class="m-menu__link-text">Extras</span>
							</a>
						</li>
						<li class="m-menu__item <?php if ($controller == 'option'){ echo $active; }; ?>" m-menu-link-redirect="1" aria-haspopup="true">
							<a href="/option" class="m-menu__link ">
								<i class="m-menu__link-icon flaticon-support"></i><span class="m-menu__link-text">Options</span>
							</a>
						</li>
						<li class="m-menu__item <?php if ($controller == 'optionset'){ echo $active; }; ?>" m-menu-link-redirect="1" aria-haspopup="true">
							<a href="/optionset" class="m-menu__link ">
								<i class="m-menu__link-icon flaticon-support"></i><span class="m-menu__link-text">Option Sets</span>
							</a>
						</li>
					</ul>
				</div>
			</li>
			<!-- Orders menu -->
			<li class="m-menu__item <?php if (in_array($controller, ['order', 'coupon', 'deal'])){ echo $activeTab; }; ?> m-menu__item--submenu m-menu__item--tabs" m-menu-submenu-toggle="tab" aria-haspopup="true">
				<a href="javascript:;" class="m-menu__link m-menu__toggle" title="Non functional dummy link">
				<span class="m-menu__link-text">Orders</span>
					<i class="m-menu__hor-arrow la la-angle-down"></i><i class="m-menu__ver-arrow la la-angle-right"></i>
				</a>
				<div class="m-menu__submenu m-menu__submenu--classic m-menu__submenu--left m-menu__submenu--tabs">
					<span class="m-menu__arrow m-menu__arrow--adjust"></span>
					<ul class="m-menu__subnav">
						<li class="m-menu__item <?php if ($controller == 'order'){ echo $active; }; ?>" m-menu-link-redirect="1" aria-haspopup="true">
							<a href="/order" class="m-menu__link ">
								<i class="m-menu__link-icon flaticon-support"></i><span class="m-menu__link-text">Orders</span>
							</a>
						</li>
						<li class="m-menu__item <?php if ($controller == 'coupon'){ echo $active; }; ?>" m-menu-link-redirect="1" aria-haspopup="true">
							<a href="/coupon" class="m-menu__link ">
								<i class="m-menu__link-icon flaticon-support"></i><span class="m-menu__link-text">Coupons</span>
							</a>
						</li>
						<li class="m-menu__item <?php if ($controller == 'deal'){ echo $active; }; ?>" m-menu-link-redirect="1" aria-haspopup="true">
							<a href="/deal" class="m-menu__link ">
								<i class="m-menu__link-icon flaticon-support"></i><span class="m-menu__link-text">Deals</span>
							</a>
						</li>
					</ul>
				</div>
			</li>
			<!-- Stock menu -->
			<li class="m-menu__item <?php if (in_array($controller, ['stock', 'stockorders', 'stockwastage'])){ echo $activeTab; }; ?> m-menu__item--submenu m-menu__item--tabs" m-menu-submenu-toggle="tab" aria-haspopup="true">
				<a href="javascript:;" class="m-menu__link m-menu__toggle" title="Non functional dummy link">
				<span class="m-menu__link-text">Stock</span>
					<i class="m-menu__hor-arrow la la-angle-down"></i><i class="m-menu__ver-arrow la la-angle-right"></i>
				</a>
				<div class="m-menu__submenu m-menu__submenu--classic m-menu__submenu--left m-menu__submenu--tabs">
					<span class="m-menu__arrow m-menu__arrow--adjust"></span>
					<ul class="m-menu__subnav">
						<li class="m-menu__item <?php if ($controller == 'stock'){ echo $active; }; ?>" m-menu-link-redirect="1" aria-haspopup="true">
							<a href="/stock" class="m-menu__link ">
								<i class="m-menu__link-icon flaticon-support"></i><span class="m-menu__link-text">stocks List</span>
							</a>
						</li>
						<li class="m-menu__item <?php if ($controller == 'stockorders'){ echo $active; }; ?>" m-menu-link-redirect="1" aria-haspopup="true">
							<a href="/stockorders" class="m-menu__link ">
								<i class="m-menu__link-icon flaticon-support"></i><span class="m-menu__link-text">Stock Orders</span>
							</a>
						</li>
						<li class="m-menu__item <?php if ($controller == 'stockwastage'){ echo $active; }; ?>" m-menu-link-redirect="1" aria-haspopup="true">
							<a href="/stockwastage" class="m-menu__link ">
								<i class="m-menu__link-icon flaticon-support"></i><span class="m-menu__link-text">Stock Wastage</span>
							</a>
						</li>
					</ul>
				</div>
			</li>
			<!-- Faculty menu -->
			<li class="m-menu__item <?php if (in_array($controller, ['staff', 'users', 'profiles', 'permissions'])){ echo $activeTab; }; ?> m-menu__item--submenu m-menu__item--tabs" m-menu-submenu-toggle="tab" aria-haspopup="true">
				<a href="javascript:;" class="m-menu__link m-menu__toggle" title="Non functional dummy link">
				<span class="m-menu__link-text">Faculty</span>
					<i class="m-menu__hor-arrow la la-angle-down"></i><i class="m-menu__ver-arrow la la-angle-right"></i>
				</a>
				<div class="m-menu__submenu m-menu__submenu--classic m-menu__submenu--left m-menu__submenu--tabs">
					<span class="m-menu__arrow m-menu__arrow--adjust"></span>
					<ul class="m-menu__subnav">
						<li class="m-menu__item <?php if ($controller == 'staff'){ echo $active; }; ?>" m-menu-link-redirect="1" aria-haspopup="true">
							<a href="/staff" class="m-menu__link ">
								<i class="m-menu__link-icon flaticon-support"></i><span class="m-menu__link-text">Current Staff</span>
							</a>
						</li>
						<?php if ($ident['profile'] == 'Administrators'):?>
						<li class="m-menu__item <?php if ($controller == 'users'){ echo $active; }; ?>" m-menu-link-redirect="1" aria-haspopup="true">
							<a href="/users" class="m-menu__link ">
								<i class="m-menu__link-icon flaticon-support"></i><span class="m-menu__link-text">Users</span>
							</a>
						</li>
						<?php endif;?>
						<li class="m-menu__item <?php if ($controller == 'profiles'){ echo $active; }; ?>" m-menu-link-redirect="1" aria-haspopup="true">
							<a href="/profiles" class="m-menu__link ">
								<i class="m-menu__link-icon flaticon-support"></i><span class="m-menu__link-text">User Roles</span>
							</a>
						</li>
						<li class="m-menu__item <?php if ($controller == 'permissions'){ echo $active; }; ?>" m-menu-link-redirect="1" aria-haspopup="true">
							<a href="/permissions" class="m-menu__link ">
								<i class="m-menu__link-icon flaticon-support"></i><span class="m-menu__link-text">Permission Management</span>
							</a>
						</li>
					</ul>
				</div>
			</li>
		</ul>
	</div>
</div>
<?php endif;?>