<?php

use Models\Accounts\BookedProducts;

$bookedproduct = new BookedProducts();
?>
<div class="mb-4">
    <?php if ($this->flashSession->output()) { ?>
        <div class="alert alert-success"><?php echo $this->flashSession->output(); ?></div>
    <?php } ?>
</div>

    <div class="col-md-12">
        <div class="card card-custom gutter-b example example-compact mb-0">
            <div class="card-body pb-0  ">
                <div class="row">
                    <div class="col-md-4">
                        <div class="card-title">
                            <h3 class="card-label pt-5">
                                CREATE NEW Service
                            </h3>
                        </div>
                    </div>
                    <div class="col-md-8 text-right pt-5">
                        <a href="/mechanics"   class="btn btn-primary mr-2">Back</a>
                    </div>

                </div>
            </div>
        </div>
            <div class="card-body formsection mt-0">
                <div class="col-lg-12">
                    <div class="m-portlet m-portlet--primary m-portlet--head-solid-bg m-portlet--bordered">

                        <form class="m-form m-form--fit m-form--label-align-right" enctype="multipart/form-data" method="post">
                            <div class="m-portlet__body">
                                <div class="m-form__section m-form__section--first ">
                                    <div class="form-group m-form__group row">
                                        <div class="col-lg-3">
                                            <div class="form-group m-form__group has-success"><label for="name">Category:</label>
                                                <input type="text" id="opgroup" name="opgroup" value="Service" readonly
                                                       class="form-control form-control-success m-input m-input--air m-input--pill"
                                                       placeholder="Group Name">
                                            </div>
                                        </div>
                                        <div class="col-lg-4" style="display:none;">
                                            <div class="form-group m-form__group has-success"><label
                                                        for="ict_cordinator">Key:</label> <input type="text" id="key"
                                                                                                 name="key"
                                                                                                 class="form-control form-control-success m-input m-input--air m-input--pill"
                                                                                                 placeholder="Key">
                                                 </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <div class="form-group m-form__group has-success"><label
                                                        for="ict_cordinator">Product Name:</label> <input type="text"
                                                                                                   id="value"
                                                                                                   name="value"
                                                                                                   class="form-control form-control-success m-input m-input--air m-input--pill"
                                                                                                   placeholder="Value">
                                                 </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <div class="form-group m-form__group has-success"><label
                                                        for="ict_cordinator">Company Name:</label>
                                                <select name="company" class="form-group form-control">
                                                    <option value="DKU">DKU</option>
                                                    <option value="All Parts">All Parts</option>
                                                </select>

                                                 </div>
                                        </div>
                                        <div class="col-lg-3" style="display: none;">
                                            <div class="form-group m-form__group has-success"><label
                                                        for="ict_cordinator">Image:</label> <input type="file"
                                                                                                    name="image"
                                                                                                   class="form-control form-control-success m-input m-input--air m-input--pill"
                                                                                                    >
                                                 </div>
                                        </div>
                                        <div class="col-md-12 float-right">
                                            <input type="submit" value="submit"
                                                   class="btn m-btn float-right btn-primary m-btn--gradient-to-info uppercase">
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div
