<?php

?>
<div class="col-md-6">
	<div class="card card-custom gutter-b example example-compact">
		<div class="card-header">
			<div class="card-title">
				<h3 class="card-label">
					Create New Role
				</h3>
			</div>
			<div class="card-toolbar">
				<div class="example-tools justify-content-center">
					<a href="/profiles" class="btn btn-hover-bg-primary btn-text-primary btn-hover-text-white border-0 font-weight-bold mr-2">
						<span class="svg-icon svg-icon-md"><!--begin::Svg Icon | path:assets/media/svg/icons/Design/Flatten.svg--><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
					    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
					        <rect x="0" y="0" width="24" height="24"/>
					        <circle fill="#000000" cx="9" cy="15" r="6"/>
					        <path d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z" fill="#000000" opacity="0.3"/>
					    </g>
					</svg><!--end::Svg Icon--></span>	Back
					</a>
				</div>
			</div>
		</div>
		<form class="form" method="post">
			<div class="card-body">
	       		<div class="form-group">
					<label>Profile Name</label>
					<?php echo $form->render('name');?>
					<span class="form-text text-muted">Enter Profile name.</span>
				</div>
				<div class="form-group">
					<label>Active Profile</label>
					<?php echo $form->render('active');?>
					<span class="form-text text-muted">Active Profile or not.</span>
				</div>
			</div>
			<div class="card-footer">
				<div class="row">
					<div class="col text-left">
						<?php echo $form->render('Submit');?>
					</div>
					<div class="col text-right">
						<button type="reset" class="btn btn-secondary">Cancel</button>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>