<!--<link href="/theme/assets/css/demo1/pages/login/login-4.css" rel="stylesheet" type="text/css"/>-->
<body class="loginbody">
    <!-- begin:: Page -->
	<div class="left">
		<?php echo $this->getContent(); ?>
	</div>
	<div class="right">
	
	</div>
	<!--<div class="kt-grid kt-grid--ver kt-grid--root">
		<div class="kt-grid kt-grid--hor kt-grid--root  kt-login kt-login--v4 kt-login--signin" id="kt_login">
			<div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor loginbg" style="background-image: url(/theme/assets/media/bg/bg-7.jpg);">
				
			</div>
		</div>	
	</div>-->
	<!--begin::Page Scripts(used by this page) -->
    <!--<script src="./assets/js/demo1/pages/login/login-general.js" type="text/javascript"></script>-->
    <!--end::Page Scripts -->
</body>
<style>
body.loginbody 
{
    display: flex;
}
body.loginbody .left {
    flex: 0 0 calc(35% - 8em);
    padding: 4em;
	display: flex;
    align-items: center;
	background: #2b2b2b;
    color: white;
}
body.loginbody .left label
{
	color:white;
}
.login-form {
    flex: 1 1 100%;
}
body.loginbody .right {
    flex: 0 0 65%;
    background-image: url(/assets/img/loginposter.jpg);
    background-size: cover;
    background-position: center;
}
.mb-3
{
	margin-bottom:2em;
}

h2.signin
{
	color: #4c97fa;
}
input.loginbtn {
    background: #4c97fa;
    color: white;
    border-color: #359ea1;
    text-transform: none;
    font-size: 1em;
    font-weight: 400;
}

.button-left {
    width: 50%;
    display: inline-block;
}
.help {
    width: 49%;
    display: inline-block;
    text-align: right;
    vertical-align: text-bottom;
}

.alert {
    padding: 5px 0;
    margin-bottom: 10px;
}
.alert.alert-outline-info {
    color: var(--info);
}
.alert.alert-outline-danger {
    color: var(--danger);
}
</style>
<!-- end:: Page -->