<?php
echo $this->getContent();
?>
<div class="row">
	<div class="columns twelve">
		<table class="table datatable">
			<thead class="thead-light">
				<tr>
					<th class="checkcol"><label class="all"><input type="checkbox" class="all"/><i class="lni lni-checkmark"></i></label></th>
					<th>Account Number</th>
					<th>Company Name</th>
					<th>Email</th>
					<th>Telephone</th>
					<th>Telephone 2</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($records as $record) : ?>
					<tr data-route="/accounts/edit/<?php echo $record->id; ?>">
						<td class="checkcol"><label><input type="checkbox" value="<?php echo $record->id; ?>"><i class="lni lni-checkmark"></i></label></div>
						<td><?php echo $record->accountnumber; ?> </td>
						<td><?php echo $record->companyname; ?> </td>
						<td><?php echo $record->email; ?> </td>
						<td><?php echo $record->telephone; ?> </td>
						<td><?php echo $record->telephone2; ?> </td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>

